# Generated by Django 3.1.2 on 2020-10-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(help_text='X coordinate of sighting', max_length=25)),
                ('latitude', models.FloatField(help_text='Y coordinate of sighting', max_length=25)),
                ('unique_squirrel_id', models.CharField(help_text='Unique Squirrel ID', max_length=15)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=5)),
                ('date', models.DateField()),
                ('age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=10)),
                ('primary_fur_color', models.CharField(blank=True, help_text='Primary fur color', max_length=10)),
                ('location', models.CharField(help_text='the location of where the squirrel was when first sighted', max_length=50)),
                ('specific_location', models.CharField(help_text='the specific location of the squirrel', max_length=50)),
                ('running', models.BooleanField(help_text='Whether or not squirrel is running')),
                ('chasing', models.BooleanField(help_text='Whether or not squirrel is chasing')),
                ('climbing', models.BooleanField(help_text='Whether or not squirrel is climbing')),
                ('eating', models.BooleanField(help_text='Whether or not squirrel is eating')),
                ('foraging', models.BooleanField(help_text='Whether or not squirrell is foraging')),
                ('other_activities', models.TextField(blank=True, max_length=300)),
                ('kuks', models.BooleanField(help_text='Whether or not squirrel kuks')),
                ('quaas', models.BooleanField(help_text='Whether or not squirrel quaas')),
                ('moans', models.BooleanField(help_text='Whether or not squirrel moans')),
                ('tail_flags', models.BooleanField(help_text='Whether or not squirrel tail flags')),
                ('tail_twitches', models.BooleanField(help_text='Whether or not squirrel tail twitches')),
                ('approaches', models.BooleanField(help_text='Whether or not squirrel is approaching')),
                ('indifferent', models.BooleanField(help_text='Whether or not squirrel is indifferent')),
                ('runs_from', models.BooleanField(help_text='Whether or not squirrel is running from observer')),
            ],
        ),
    ]
