# Generated by Django 3.1.2 on 2020-10-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.FloatField(help_text='X coordinate of sighting', max_length=25)),
                ('y_coord', models.FloatField(help_text='Y coordinate of sighting', max_length=25)),
                ('squirrel_id', models.CharField(help_text='Unique Squirrel ID', max_length=15)),
                ('hectare', models.CharField(max_length=5)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=5)),
                ('date', models.IntegerField(help_text='Date MMDDYYYY')),
                ('hectare_num', models.IntegerField(help_text='Hectare Squirrel Number')),
                ('age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=10)),
                ('primary_fur', models.CharField(blank=True, help_text='Primary fur color', max_length=10)),
                ('highlight_fur', models.CharField(blank=True, help_text='Highlight fur color', max_length=20)),
                ('running', models.BooleanField(help_text='Whether or not squirrell is running')),
            ],
        ),
    ]
